services:
  - type: web
    name: otpas-hu-frontend
    env: node
    plan: free
    buildCommand: npm install && VITE_API_URL=https://otpas-hu-database.onrender.com npm run build
    startCommand: npm start
    envVars:
      - key: VITE_API_URL
        value: https://otpas-hu-database.onrender.com
  - type: web
    name: otpas-hu-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: otpas-hu-db
          property: connectionString
      - key: DB_HOST
        fromDatabase:
          name: otpas-hu-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: otpas-hu-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: otpas-hu-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: otpas-hu-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: otpas-hu-db
          property: password
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        value: https://otpas-hu-frontend.onrender.com

databases:
  - name: otpas-hu-db
    plan: free
    ipAllowList: []
